name: finance_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.17

  # State Management
  provider: ^6.1.2

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.2
  uuid: ^4.5.1
  # Local Storage
  shared_preferences: ^2.5.2

  # Notifications
  flutter_local_notifications: ^18.0.1


  # Splash Screen
  flutter_native_splash: ^2.4.4

  # Date & Number Formatting
  intl: ^0.18.1

  cupertino_icons: ^1.0.8
 # showing data in charts & graph
  fl_chart: ^0.65.0

#  For spacing
  gap: ^3.0.1
#  custom snack bar
  motion_toast: ^2.12.1

  animated_search_bar: ^2.8.0

  table_calendar: ^3.0.9
  icons_plus: ^5.0.0
  currency_picker: ^2.0.21

  # Google Sign-In
  google_sign_in: ^5.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    # App Icon Generator
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^4.0.0



  # App Icon Configuration   flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/finance_app_logo.png"
  min_sdk_android: 21
#  remove_alpha_ios: true
  web:
    generate: false

# Splash Screen Configuration   flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/finance_app_logo.png
  color_dark: "#121212"
  image_dark: assets/icons/finance_app_logo.png

  android_12:
    image: assets/icons/finance_app_logo.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/icons/finance_app_logo.png
    icon_background_color_dark: "#121212"

  web: false
  ios: true
  android: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
